name: Run tests

on:
  workflow_dispatch:

jobs:
  Building-app-and-running-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        run: chrome --version

      - name: Run tests
        run: |
          mvn test -Dusername=standard_user -Dpassword=secret_sauce